/*!
 @file           test_notefreqs.c
 @brief          Note frequency test
 @author         tqfx tqfx@foxmail.com
 @version        0
 @date           2021-05-22
 @copyright      Copyright (C) 2021 tqfx
 \n \n
 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:
 \n \n
 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.
 \n \n
 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.
*/

#include <stdio.h>

#define NOTEFREQS_PROPORT ((180000000 >> 1) / 200)
#define NOTEFREQS_TYPE    double
#include "ca.h"

static double song[][2] = {
    {NOTEFREQS_FREQ_C0, NOTEFREQS_C0},
    {NOTEFREQS_FREQ_Db0, NOTEFREQS_Db0},
    {NOTEFREQS_FREQ_D0, NOTEFREQS_D0},
    {NOTEFREQS_FREQ_Eb0, NOTEFREQS_Eb0},
    {NOTEFREQS_FREQ_E0, NOTEFREQS_E0},
    {NOTEFREQS_FREQ_F0, NOTEFREQS_F0},
    {NOTEFREQS_FREQ_Gb0, NOTEFREQS_Gb0},
    {NOTEFREQS_FREQ_G0, NOTEFREQS_G0},
    {NOTEFREQS_FREQ_Ab0, NOTEFREQS_Ab0},
    {NOTEFREQS_FREQ_A0, NOTEFREQS_A0},
    {NOTEFREQS_FREQ_Bb0, NOTEFREQS_Bb0},
    {NOTEFREQS_FREQ_B0, NOTEFREQS_B0},
    {NOTEFREQS_FREQ_C1, NOTEFREQS_C1},
    {NOTEFREQS_FREQ_Db1, NOTEFREQS_Db1},
    {NOTEFREQS_FREQ_D1, NOTEFREQS_D1},
    {NOTEFREQS_FREQ_Eb1, NOTEFREQS_Eb1},
    {NOTEFREQS_FREQ_E1, NOTEFREQS_E1},
    {NOTEFREQS_FREQ_F1, NOTEFREQS_F1},
    {NOTEFREQS_FREQ_Gb1, NOTEFREQS_Gb1},
    {NOTEFREQS_FREQ_G1, NOTEFREQS_G1},
    {NOTEFREQS_FREQ_Ab1, NOTEFREQS_Ab1},
    {NOTEFREQS_FREQ_A1, NOTEFREQS_A1},
    {NOTEFREQS_FREQ_Bb1, NOTEFREQS_Bb1},
    {NOTEFREQS_FREQ_B1, NOTEFREQS_B1},
    {NOTEFREQS_FREQ_C2, NOTEFREQS_C2},
    {NOTEFREQS_FREQ_Db2, NOTEFREQS_Db2},
    {NOTEFREQS_FREQ_D2, NOTEFREQS_D2},
    {NOTEFREQS_FREQ_Eb2, NOTEFREQS_Eb2},
    {NOTEFREQS_FREQ_E2, NOTEFREQS_E2},
    {NOTEFREQS_FREQ_F2, NOTEFREQS_F2},
    {NOTEFREQS_FREQ_Gb2, NOTEFREQS_Gb2},
    {NOTEFREQS_FREQ_G2, NOTEFREQS_G2},
    {NOTEFREQS_FREQ_Ab2, NOTEFREQS_Ab2},
    {NOTEFREQS_FREQ_A2, NOTEFREQS_A2},
    {NOTEFREQS_FREQ_Bb2, NOTEFREQS_Bb2},
    {NOTEFREQS_FREQ_B2, NOTEFREQS_B2},
    {NOTEFREQS_FREQ_C3, NOTEFREQS_C3},
    {NOTEFREQS_FREQ_Db3, NOTEFREQS_Db3},
    {NOTEFREQS_FREQ_D3, NOTEFREQS_D3},
    {NOTEFREQS_FREQ_Eb3, NOTEFREQS_Eb3},
    {NOTEFREQS_FREQ_E3, NOTEFREQS_E3},
    {NOTEFREQS_FREQ_F3, NOTEFREQS_F3},
    {NOTEFREQS_FREQ_Gb3, NOTEFREQS_Gb3},
    {NOTEFREQS_FREQ_G3, NOTEFREQS_G3},
    {NOTEFREQS_FREQ_Ab3, NOTEFREQS_Ab3},
    {NOTEFREQS_FREQ_A3, NOTEFREQS_A3},
    {NOTEFREQS_FREQ_Bb3, NOTEFREQS_Bb3},
    {NOTEFREQS_FREQ_B3, NOTEFREQS_B3},
    {NOTEFREQS_FREQ_C4, NOTEFREQS_C4},
    {NOTEFREQS_FREQ_Db4, NOTEFREQS_Db4},
    {NOTEFREQS_FREQ_D4, NOTEFREQS_D4},
    {NOTEFREQS_FREQ_Eb4, NOTEFREQS_Eb4},
    {NOTEFREQS_FREQ_E4, NOTEFREQS_E4},
    {NOTEFREQS_FREQ_F4, NOTEFREQS_F4},
    {NOTEFREQS_FREQ_Gb4, NOTEFREQS_Gb4},
    {NOTEFREQS_FREQ_G4, NOTEFREQS_G4},
    {NOTEFREQS_FREQ_Ab4, NOTEFREQS_Ab4},
    {NOTEFREQS_FREQ_A4, NOTEFREQS_A4},
    {NOTEFREQS_FREQ_Bb4, NOTEFREQS_Bb4},
    {NOTEFREQS_FREQ_B4, NOTEFREQS_B4},
    {NOTEFREQS_FREQ_C5, NOTEFREQS_C5},
    {NOTEFREQS_FREQ_Db5, NOTEFREQS_Db5},
    {NOTEFREQS_FREQ_D5, NOTEFREQS_D5},
    {NOTEFREQS_FREQ_Eb5, NOTEFREQS_Eb5},
    {NOTEFREQS_FREQ_E5, NOTEFREQS_E5},
    {NOTEFREQS_FREQ_F5, NOTEFREQS_F5},
    {NOTEFREQS_FREQ_Gb5, NOTEFREQS_Gb5},
    {NOTEFREQS_FREQ_G5, NOTEFREQS_G5},
    {NOTEFREQS_FREQ_Ab5, NOTEFREQS_Ab5},
    {NOTEFREQS_FREQ_A5, NOTEFREQS_A5},
    {NOTEFREQS_FREQ_Bb5, NOTEFREQS_Bb5},
    {NOTEFREQS_FREQ_B5, NOTEFREQS_B5},
    {NOTEFREQS_FREQ_C6, NOTEFREQS_C6},
    {NOTEFREQS_FREQ_Db6, NOTEFREQS_Db6},
    {NOTEFREQS_FREQ_D6, NOTEFREQS_D6},
    {NOTEFREQS_FREQ_Eb6, NOTEFREQS_Eb6},
    {NOTEFREQS_FREQ_E6, NOTEFREQS_E6},
    {NOTEFREQS_FREQ_F6, NOTEFREQS_F6},
    {NOTEFREQS_FREQ_Gb6, NOTEFREQS_Gb6},
    {NOTEFREQS_FREQ_G6, NOTEFREQS_G6},
    {NOTEFREQS_FREQ_Ab6, NOTEFREQS_Ab6},
    {NOTEFREQS_FREQ_A6, NOTEFREQS_A6},
    {NOTEFREQS_FREQ_Bb6, NOTEFREQS_Bb6},
    {NOTEFREQS_FREQ_B6, NOTEFREQS_B6},
    {NOTEFREQS_FREQ_C7, NOTEFREQS_C7},
    {NOTEFREQS_FREQ_Db7, NOTEFREQS_Db7},
    {NOTEFREQS_FREQ_D7, NOTEFREQS_D7},
    {NOTEFREQS_FREQ_Eb7, NOTEFREQS_Eb7},
    {NOTEFREQS_FREQ_E7, NOTEFREQS_E7},
    {NOTEFREQS_FREQ_F7, NOTEFREQS_F7},
    {NOTEFREQS_FREQ_Gb7, NOTEFREQS_Gb7},
    {NOTEFREQS_FREQ_G7, NOTEFREQS_G7},
    {NOTEFREQS_FREQ_Ab7, NOTEFREQS_Ab7},
    {NOTEFREQS_FREQ_A7, NOTEFREQS_A7},
    {NOTEFREQS_FREQ_Bb7, NOTEFREQS_Bb7},
    {NOTEFREQS_FREQ_B7, NOTEFREQS_B7},
    {NOTEFREQS_FREQ_C8, NOTEFREQS_C8},
    {NOTEFREQS_FREQ_Db8, NOTEFREQS_Db8},
    {NOTEFREQS_FREQ_D8, NOTEFREQS_D8},
    {NOTEFREQS_FREQ_Eb8, NOTEFREQS_Eb8},
    {NOTEFREQS_FREQ_E8, NOTEFREQS_E8},
    {NOTEFREQS_FREQ_F8, NOTEFREQS_F8},
    {NOTEFREQS_FREQ_Gb8, NOTEFREQS_Gb8},
    {NOTEFREQS_FREQ_G8, NOTEFREQS_G8},
    {NOTEFREQS_FREQ_Ab8, NOTEFREQS_Ab8},
    {NOTEFREQS_FREQ_A8, NOTEFREQS_A8},
    {NOTEFREQS_FREQ_Bb8, NOTEFREQS_Bb8},
    {NOTEFREQS_FREQ_B8, NOTEFREQS_B8},
};

int main(void)
{
    unsigned int song_n = sizeof(song) / sizeof(*song);
    for (unsigned int i = 0; i != song_n; ++i)
    {
        printf("%g\t%g\r\n", song[i][0], song[i][1]);
    }

    return 0;
}

/* END OF FILE */
