target("test-a")
    set_group("test")
    set_default(false)
    set_kind("binary")
    add_files("a.cpp")
    add_deps("a")
target_end()

target("test-for")
    set_group("test")
    set_default(false)
    set_kind("binary")
    add_files("for.c", "for.cpp")
    add_deps("a")
target_end()

target("test-version")
    set_group("test")
    set_default(false)
    set_kind("binary")
    add_files("version.cpp")
    add_deps("a")
target_end()

target("test-real")
    set_group("test")
    set_default(false)
    set_kind("binary")
    add_files("real.c")
    add_deps("a")
target_end()

target("test-math")
    set_group("test")
    set_default(false)
    set_kind("binary")
    add_files("math.c")
    add_deps("a")
target_end()

target("test-arr")
    set_group("test")
    set_default(false)
    set_kind("binary")
    add_files("arr.c", "arr.cpp")
    add_deps("a")
target_end()

target("test-list")
    set_group("test")
    set_default(false)
    set_kind("binary")
    add_files("list.c", "list.cpp")
    add_deps("a")
target_end()

target("test-slist")
    set_group("test")
    set_default(false)
    set_kind("binary")
    add_files("slist.c", "slist.cpp")
    add_deps("a")
target_end()

target("test-operator")
    set_group("test")
    set_default(false)
    set_kind("binary")
    add_files("operator.c")
    add_deps("a")
target_end()

includes("misc")
includes("host")
