add_rules("mode.check", "mode.debug", "mode.release")

set_project("liba")
set_version("0.1.0", {build = "%Y%m%d%H%M"})
set_description("An algorithm library based on C/C++ language")
set_languages("c11", "c++17")
set_warnings("everything")

target("a")
    set_kind("static")
    add_files("src/**.c")
    add_includedirs("include", {public = true})
    set_configdir("$(curdir)/src")
    add_configfiles("xmake/config.h")
    add_links("m")
target_end()

target("aa")
    set_kind("static")
    add_files("src/**.cpp")
    add_includedirs("include", {public = true})
    set_configdir("$(curdir)/src")
    add_configfiles("xmake/config.hpp")
    add_links("m")
target_end()
