target("test-str")
    set_group("test")
    set_default(false)
    set_kind("binary")
    add_files("str.c")
    add_deps("a")
target_end()

target("test-str+")
    set_group("test")
    set_default(false)
    set_kind("binary")
    add_files("str.cc")
    add_deps("a")
target_end()

target("test-vec")
    set_group("test")
    set_default(false)
    set_kind("binary")
    add_files("vec.c")
    add_deps("a")
target_end()

target("test-vec+")
    set_group("test")
    set_default(false)
    set_kind("binary")
    add_files("vec.cc")
    add_deps("a")
target_end()
