/*!
 @file a.config.h
 @brief algorithm library configuration
 @details it is autogenerated by xmake ${XMAKE_VERSION}
 @copyright Copyright (C) 2020-present tqfx, All rights reserved.
*/

#ifndef LIBA_CONFIG_H
#define LIBA_CONFIG_H

/* clang-format off */
#define A_VERSION "${VERSION}"
#define A_VERSION_MAJOR ${VERSION_MAJOR}
#define A_VERSION_MINOR ${VERSION_MINOR}
#define A_VERSION_PATCH ${VERSION_ALTER}
#define A_VERSION_TWEAK A_U64_C(${VERSION_BUILD})
/* clang-format on */

#endif /* LIBA_CONFIG_H */
