/*!
 @file a.config.h
 @brief algorithm library configuration
 @details it is autogenerated by xmake ${XMAKE_VERSION}
 @copyright Copyright (C) 2020-present tqfx, All rights reserved.
*/

#ifndef __A_CONFIG_H__
#define __A_CONFIG_H__

// clang-format off

#define A_VERSION_MAJOR ${VERSION_MAJOR}
#define A_VERSION_MINOR ${VERSION_MINOR}
#define A_VERSION_PATCH ${VERSION_ALTER}
#define A_VERSION_TWEAK ${VERSION_BUILD}

// clang-format on

/*! algorithm library version string */
#define A_VERSION "${VERSION}"

#endif /* __A_CONFIG_H__ */
