#!/usr/bin/env lua

package.path = arg[0]:sub(0, -arg[0]:match("([^/\\]*)$"):len() - 1) .. "?.lua;" .. package.path
local test = require("test")
local a = require("liba")
test:r(getmetatable(a.pid))
assert(a.pid.new(1, -10, 10))
assert(a.pid.new(1, -10, 10, 10))
assert(a.pid.new(1, 10, 0.1, 1, -10, 10))
assert(a.pid.new(1, 10, 0.1, 1, -10, 10, 10))
pid = a.pid.new(1, 10, 0.1, 1, -10, 10, 10)
assert(a.pid.kpid(pid, 3, 2, 1))
assert(a.pid:kpid(pid, 3, 2, 1))
assert(a.pid.proc(pid, 1, 0))
assert(a.pid:proc(pid, 1, 0))
assert(a.pid.time(pid, 0.1))
assert(a.pid:time(pid, 0.1))
assert(a.pid.zero(pid))
assert(a.pid:zero(pid))
assert(a.pid.pos(pid, 10))
assert(a.pid:pos(pid, 10))
assert(a.pid.inc(pid))
assert(a.pid:inc(pid))
assert(a.pid.off(pid))
assert(a.pid:off(pid))
tab = a.pid.into(pid)
pid = a.pid.from(tab)
tab = a.pid:into(pid)
pid = a.pid:from(tab)
test:r(getmetatable(pid))
pid = a:pid(1, 10, 0.1, 1, -10, 10, 10)
pid:kpid(3, 2, 1):time(0.1):off():inc():pos(10)
assert(pid:from(tab))
assert(pid:into())
assert(pid(1, 0))
