#!/usr/bin/env lua

package.path = arg[0]:sub(0, -arg[0]:match("([^/\\]*)$"):len() - 1) .. "?.lua;" .. package.path
local test = require("test")
local a = require("liba")
test:r(getmetatable(a.pid))

pid = a.pid.init(1, 10, 0.1, 1, -10, 10, 10)
a.pid.kpid(pid, 3, 2, 1)
a.pid:kpid(pid, 3, 2, 1)
a.pid.proc(pid, 1, 0)
a.pid:proc(pid, 1, 0)
a.pid.time(pid, 0.1)
a.pid:time(pid, 0.1)
a.pid.done(pid)
a.pid:done(pid)
a.pid.pos(pid, 10)
a.pid:pos(pid, 10)
a.pid.inc(pid)
a.pid:inc(pid)
a.pid.off(pid)
a.pid:off(pid)
tab = a.pid.into(pid)
pid = a.pid.from(tab)
tab = a.pid:into(pid)
pid = a.pid:from(tab)

pid = a:pid(1, 10, 0.1, 1, -10, 10, 10)
test:r(pid)
pid:kpid(3, 2, 1):time(0.1):off(1, 2):inc():pos(10)
pid:from(tab)
pid:into()
pid(1, 0)
