#!/usr/bin/env bash
IFS=$'\n'
sources=$(find include src test ffi/lua ffi/java ffi/javascript -regex ".*\.\(c\|h\|cc\|hh\|cpp\|hpp\|cxx\|hxx\)")
clang-format -style=file -i $sources --verbose
black -S .
