/*!
 @file a.config.h
 @brief algorithm library configuration
 @details it is autogenerated by cmake @CMAKE_VERSION@
 @copyright Copyright (C) 2020-present tqfx, All rights reserved.
*/

#ifndef LIBA_CONFIG_H
#define LIBA_CONFIG_H

/* clang-format off */
#cmakedefine A_SIZEOF_P @A_SIZEOF_P@
#cmakedefine A_VERSION "@A_VERSION@"
#cmakedefine A_VERSION_MAJOR @A_VERSION_MAJOR@
#cmakedefine A_VERSION_MINOR @A_VERSION_MINOR@
#cmakedefine A_VERSION_PATCH @A_VERSION_PATCH@
#cmakedefine A_VERSION_TWEAK A_U64_C(@A_VERSION_TWEAK@)
/* clang-format on */

#endif /* LIBA_CONFIG_H */
