/*!
 @file a.config.h
 @brief algorithm library configuration
 @details it is autogenerated by cmake @CMAKE_VERSION@
 @copyright Copyright (C) 2020-present tqfx, All rights reserved.
*/

#ifndef LIBA_CONFIG_H
#define LIBA_CONFIG_H

/* clang-format off */

#if !defined A_SIZE_REAL
#cmakedefine A_SIZE_REAL @A_SIZE_REAL@
#endif /* A_SIZE_REAL */
#cmakedefine A_SIZE_VPTR @A_SIZE_VPTR@
#cmakedefine A_BYTE_ORDER @A_BYTE_ORDER@
#cmakedefine A_VERSION "@A_VERSION@"
#cmakedefine A_VERSION_MAJOR @A_VERSION_MAJOR@
#cmakedefine A_VERSION_MINOR @A_VERSION_MINOR@
#cmakedefine A_VERSION_PATCH @A_VERSION_PATCH@
#cmakedefine A_VERSION_TWEAK A_U64_C(@A_VERSION_TWEAK@)

#cmakedefine A_HAVE_COMPLEX_H @A_HAVE_COMPLEX_H@
#cmakedefine A_HAVE_STDINT_H @A_HAVE_STDINT_H@
#cmakedefine A_HAVE_HYPOT @A_HAVE_HYPOT@
#cmakedefine A_HAVE_LOG1P @A_HAVE_LOG1P@
#cmakedefine A_HAVE_ATAN2 @A_HAVE_ATAN2@
#cmakedefine A_HAVE_CSQRT @A_HAVE_CSQRT@
#cmakedefine A_HAVE_CPOW @A_HAVE_CPOW@
#cmakedefine A_HAVE_CEXP @A_HAVE_CEXP@
#cmakedefine A_HAVE_CLOG @A_HAVE_CLOG@
#cmakedefine A_HAVE_CSIN @A_HAVE_CSIN@
#cmakedefine A_HAVE_CCOS @A_HAVE_CCOS@
#cmakedefine A_HAVE_CTAN @A_HAVE_CTAN@
#cmakedefine A_HAVE_CSINH @A_HAVE_CSINH@
#cmakedefine A_HAVE_CCOSH @A_HAVE_CCOSH@
#cmakedefine A_HAVE_CTANH @A_HAVE_CTANH@
#cmakedefine A_HAVE_CASIN @A_HAVE_CASIN@
#cmakedefine A_HAVE_CACOS @A_HAVE_CACOS@
#cmakedefine A_HAVE_CATAN @A_HAVE_CATAN@
#cmakedefine A_HAVE_CASINH @A_HAVE_CASINH@
#cmakedefine A_HAVE_CACOSH @A_HAVE_CACOSH@
#cmakedefine A_HAVE_CATANH @A_HAVE_CATANH@

/* clang-format on */

#endif /* LIBA_CONFIG_H */
