if("${CMAKE_C_COMPILER_ID}" STREQUAL "GNU" OR "${CMAKE_C_COMPILER_ID}" STREQUAL "Clang" OR
  "${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU" OR "${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang")
  list(APPEND FLAG_CHECKS -fsanitize=address)
  list(APPEND FLAG_CHECKS -fsanitize=undefined)
  list(APPEND FLAG_CHECKS -fno-sanitize-recover)
  list(APPEND FLAG_CHECKS -fno-omit-frame-pointer)
  list(APPEND FLAG_CHECKS -fsanitize=float-cast-overflow)
elseif("${CMAKE_C_COMPILER_ID}" STREQUAL "MSVC" OR "${CMAKE_CXX_COMPILER_ID}" STREQUAL "MSVC")
  add_compile_options(/fsanitize=address)
endif()
# C and C++
foreach(flag ${FLAG_CHECKS})
  if(NOT ${flag} IN_LIST FLAG_CHECKED_CC)
    list(APPEND FLAG_CHECKED_CC ${flag})
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${flag}")
  endif()
  if(NOT ${flag} IN_LIST FLAG_CHECKED_CXX)
    list(APPEND FLAG_CHECKED_CXX ${flag})
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${flag}")
  endif()
endforeach()
