cmake_host_system_information(RESULT OS_PLATFORM QUERY OS_PLATFORM)
cmake_host_system_information(RESULT OS_NAME QUERY OS_NAME)
set(CMAKE_CXX_COMPILER 0)

find_program(CMAKE_C_COMPILER tcc)
set(CMAKE_C_FLAGS_RELEASE_INIT -O2)
set(CMAKE_C_FLAGS_MINSIZEREL_INIT -Os)
set(CMAKE_C_FLAGS_RELWITHDEBINFO_INIT -O2)

find_program(CMAKE_AR tcc)
set(CMAKE_C_ARCHIVE_CREATE "<CMAKE_AR> -ar qc <TARGET> <LINK_FLAGS> <OBJECTS>")
set(CMAKE_C_ARCHIVE_APPEND "<CMAKE_AR> -ar q <TARGET> <LINK_FLAGS> <OBJECTS>")

if(ANDROID)
  string(TOLOWER ${OS_PLATFORM}-${OS_NAME}-android CMAKE_LIBRARY_ARCHITECTURE)
elseif(UNIX)
  string(TOLOWER ${OS_PLATFORM}-${OS_NAME}-gnu CMAKE_LIBRARY_ARCHITECTURE)
endif()
