name: debugger
on:
  workflow_dispatch:
jobs:
  debugger:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          submodules: true
      - name: debugger
        uses: shaowenchen/debugger-action@v2
        timeout-minutes: 360
        continue-on-error: true
        with:
          ngrok_token: ${{ secrets.NGROK_TOKEN }}
