name: deploy
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: source
      - uses: mattnotmitt/doxygen-action@v1
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: ${{ github.event.head_commit.message }}
          disable_nojekyll: true
          publish_branch: gh-pages
          force_orphan: true
          publish_dir: html
