name: freebsd
on:
  workflow_dispatch:
jobs:
  FreeBSD:
    strategy:
      fail-fast: false
      matrix:
        include: [
          { type: Debug },
          { type: RelWithDebInfo },
        ]
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          submodules: true
      - uses: vmactions/freebsd-vm@v0.1.6
        env:
          CC: clang
          CXX: clang++
        with:
          envs: 'CC CXX'
          prepare: |
            pkg install -y cmake gmake
          run: |
            cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.type }} \
              -DENABLE_WARNINGS=ON \
              -DENABLE_SANITIZE=1 \
              -DENABLE_PYTHON=ON \
              -DENABLE_VCPKG=ON \
              -DENABLE_JAVA=ON \
              -DENABLE_LUA=ON \
              -DBUILD_TESTING=ON
            cmake --build build --config ${{ matrix.type }}
            cmake --build build --target test
