name: linux
on:
  workflow_dispatch:
jobs:
  Linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: [
          { preset: debug },
          { preset: release },
        ]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          submodules: true
      - name: Run cmake
        run: |
          cmake --preset=${{ matrix.preset }} -DBUILD_TESTING=ON
          cmake --build --preset=${{ matrix.preset }} --parallel
      - name: Run ctest
        run: |
          ctest --preset=${{ matrix.preset }} --parallel
