name: unix
on:
  workflow_dispatch:
jobs:
  GNU:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cmake --preset=debug
          cmake --build --preset=debug --parallel
          ctest --preset=debug --parallel
          rm -rf build
  Apple:
    continue-on-error: true
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cmake --preset=debug
          cmake --build --preset=debug --parallel
          ctest --preset=debug --parallel
          rm -rf build
  MinGW:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install -y mingw-w64
      - run: |
          cmake --preset=mingw64 -DBUILD_TESTING=ON
          cmake --build --preset=mingw64 --parallel
          rm -rf build
      - run: |
          cmake --preset=mingw32 -DBUILD_TESTING=ON
          cmake --build --preset=mingw32 --parallel
          rm -rf build
  FreeBSD:
    continue-on-error: true
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - uses: vmactions/freebsd-vm@v0.1.6
        with:
          copyback: true
          prepare: |
            pkg install -y cmake
          run: |
            cmake --preset=debug
            cmake --build --preset=debug
            ctest --preset=debug
            rm -rf build
