name: unix
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  GNU:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Debug -DENABLE_TEST_LIBA=ON
          cmake --build build --config Debug --parallel
          cmake --build build --target test
  AppleClang:
    continue-on-error: true
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Debug -DENABLE_TEST_LIBA=ON
          cmake --build build --config Debug --parallel
          cmake --build build --target test
  mingw-w64:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install -y mingw-w64
      - run: |
          cmake -B build_w64 -DCMAKE_BUILD_TYPE=Debug -DENABLE_TEST_LIBA=ON -DCMAKE_TOOLCHAIN_FILE=cmake/mingw64.cmake
          cmake --build build_w64 --config Debug --parallel
      - run: |
          cmake -B build_w32 -DCMAKE_BUILD_TYPE=Debug -DENABLE_TEST_LIBA=ON -DCMAKE_TOOLCHAIN_FILE=cmake/mingw32.cmake
          cmake --build build_w32 --config Debug --parallel
