name: unix
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  GNU:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cmake --preset=debug
          cmake --build --preset=debug
          ctest --preset=debug
          rm -rf build
  AppleClang:
    continue-on-error: true
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cmake --preset=debug
          cmake --build --preset=debug
          ctest --preset=debug
          rm -rf build
  mingw-w64:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install -y mingw-w64
      - run: |
          cmake --preset=mingw64
          cmake --build --preset=mingw64
          rm -rf build
      - run: |
          cmake --preset=mingw32
          cmake --build --preset=mingw32
          rm -rf build
